import { esc, rub, when, csrf, hidden, stateNames } from './views.mjs';
import { deliveryNames, shipmentNames } from './checkout-data.mjs';
import { dealStates, costStatuses } from './retail.mjs';
const input = (label, name, value = '', extra = '') => `<label>${label}<input name="${name}" value="${esc(value ?? '')}" ${extra}></label>`;
const area = (label, name, value = '', max = 3000) => `<label>${label}<textarea name="${name}" maxlength="${max}">${esc(value)}</textarea></label>`;
export function customerList(retail, q, s) {
  return `<h2>Клиенты</h2><p><a class="button primary" href="/crm/customers/new">Добавить клиента</a></p><form>${input('Имя, телефон или email', 'q', q)}<button>Найти</button></form>${retail.customers(q).map(c => `<div class="box"><a href="/crm/customers/${c.id}">${esc(c.name || c.phone || 'Клиент')}</a><p>${esc(c.phone)} · ${esc(c.email)}</p><small>Заказов: ${c.order_count} · диалогов: ${c.dialog_count}${c.segment ? ` · ${esc(c.segment)}` : ''}</small></div>`).join('') || '<p>Клиенты появятся после обращения, заказа или импорта МойСклад.</p>'}`;
}
export function customerEditor(c, orders, dialogs, s) {
  return `<h2>${c ? 'Карточка клиента' : 'Новый клиент'}</h2><form method="post" action="/crm/customers/save">${csrf(s)}${hidden('id', c?.id || '')}${input('Имя', 'name', c?.name, 'maxlength="120"')}${input('Телефон', 'phone', c?.phone, 'maxlength="24"')}${input('Email', 'email', c?.email, 'maxlength="254"')}${input('Сегмент', 'segment', c?.segment, 'maxlength="100"')}${area('Заметки', 'note', c?.note)}<button class="primary">Сохранить</button></form>
    ${c ? `<p><a href="/crm/deals/new?customer=${c.id}">Создать сделку</a></p><h3>Заказы</h3>${orders.map(o => `<p><a href="/crm/orders/${o.id}">${o.id}</a> · ${esc(stateNames[o.state])}</p>`).join('') || '<p>Пока нет.</p>'}<h3>Диалоги</h3>${dialogs.map(d => `<p><a href="/crm/desk?dialog=${d.id}">${esc(d.title)}</a> · ${esc(d.label)}</p>`).join('') || '<p>Свяжите диалог с клиентом в разделе «Переписка».</p>'}${c.moysklad_id ? `<p><a href="/crm/customers/${c.id}/accounting">Продажи и возвраты МойСклад →</a></p>` : ''}` : ''}`;
}
export function dealEditor(d, customers, s, chosenCustomer = '') {
  return `<h2>${d ? 'Сделка' : 'Новая сделка'}</h2><form method="post" action="/crm/deals/save">${csrf(s)}${hidden('id', d?.id || '')}${hidden('revision', d?.revision || 0)}<label>Клиент<select name="customerId" required>${customers.map(c => `<option value="${c.id}"${c.id === (d?.customer_id || chosenCustomer) ? ' selected' : ''}>${esc(c.name || c.phone || c.email || 'Клиент')}</option>`).join('')}</select></label>${input('Название', 'title', d?.title, 'maxlength="250" required')}<label>Этап<select name="state">${Object.entries(dealStates).map(([k, v]) => `<option value="${k}"${d?.state === k ? ' selected' : ''}>${v}</option>`).join('')}</select></label>${input('Ответственный', 'responsible', d?.responsible, 'maxlength="120"')}${input('Следующее действие — московское время', 'nextAt', d?.next_at ? new Date(d.next_at+10800000).toISOString().slice(0,16) : '', 'type="datetime-local"')}${input('Причина потери', 'lostReason', d?.lost_reason, 'maxlength="200"')}${area('Заметки', 'note', d?.note)}<button class="primary">Сохранить</button></form>`;
}
export function dealsList(rows) {
  return `<h2>Сделки</h2><p><a class="button primary" href="/crm/deals/new">Новая сделка</a></p>${rows.map(d => `<div class="box"><a href="/crm/deals/${d.id}">${esc(d.title)}</a><p>${esc(dealStates[d.state])} · ${esc(d.name || d.phone)}${d.responsible ? ` · ${esc(d.responsible)}` : ''}</p><small>Следующее действие: ${when(d.next_at)}</small>${d.order_id ? `<p><a href="/crm/orders/${d.order_id}">${d.order_id}</a></p>` : ''}</div>`).join('') || '<p>Создайте первую сделку. Заказ сайта создаёт её автоматически.</p>'}`;
}
export function tasksView(rows, s) {
  return `<h2>Задачи</h2><form method="post" action="/crm/tasks/save">${csrf(s)}${input('Результат', 'title', '', 'maxlength="250" required')}${input('Ответственный', 'responsible', '', 'maxlength="120"')}${input('Срок — московское время', 'dueAt', '', 'type="datetime-local"')}<button class="primary">Добавить задачу</button></form>${rows.map(t => `<div class="box"><b>${esc(t.title)}</b>${t.customer_id?`<p><a href="/crm/customers/${t.customer_id}">${esc(t.name||'Контакт')}</a></p>`:''}<p>${esc(t.responsible || 'Ответственный не назначен')} · ${when(t.due_at)}${t.state==='open'&&t.due_at&&t.due_at<Date.now()?' · просрочено':''}</p>${t.state === 'open' ? `<form method="post" action="/crm/tasks/${t.id}/done">${csrf(s)}<button>Завершить</button></form>` : '<small>Выполнена</small>'}</div>`).join('')}`;
}
export function inboxCustomerLink(dialog, customer, customers, s) {
  return `<div class="box"><h3>Клиент CRM</h3>${customer ? `<p><a href="/crm/customers/${customer.id}">${esc(customer.name || customer.phone || 'Клиент')}</a></p>` : '<p>Клиент ещё не связан с диалогом.</p>'}<form method="post" action="/crm/inbox/${dialog.id}/link">${csrf(s)}<label>Клиент<select name="customerId" required><option value="">Выберите клиента</option>${customers.map(c => `<option value="${c.id}"${c.id === customer?.id ? ' selected' : ''}>${esc(c.name || c.phone || c.email || 'Клиент')}</option>`).join('')}</select></label><button>Связать с клиентом</button></form><p><a href="/crm/customers/new">Создать карточку клиента</a></p></div>`;
}
export function crmOrderView(o, d, retail, s) {
  const f = retail.fulfillment(o.id), proposal = retail.proposal(o.id), economics = retail.economics(o.id);
  return `<h2>${o.id}</h2><p>${when(o.created_at)}</p><div class="box"><b>${esc(d.name)}</b><p><a href="tel:${esc(d.phone)}">${esc(d.phone)}</a> · ${esc(d.email)}</p><p class="description">${esc(d.comment)}</p><p>Оплата: ${d.payment === 'invoice' ? 'Счёт ИП / организации' : 'Наличные'}</p></div>${d.lines.map(l => `<p>${esc(l.title)} × ${l.qty} — ${rub(l.priceRub)}<br><small>${esc(l.specification)}</small></p>`).join('')}<p class="price">Товары: ${rub(d.totalRub)}</p><form method="post">${csrf(s)}<label>Статус заказа<select name="state">${Object.keys(stateNames).filter(k => ['new', 'checking', 'confirmed', 'fulfilling', 'completed', 'cancelled', 'returned'].includes(k)).map(k => `<option value="${k}"${o.state === k ? ' selected' : ''}>${stateNames[k]}</option>`).join('')}</select></label>${area('Заметки по заказу', 'note', o.note, 2000)}<button>Сохранить статус</button></form>
    <section class="box"><h3>Доставка</h3><p>${esc(deliveryNames[f.data.method])} · ${esc(f.data.city || 'Грузинская, 41а')}</p><p>${esc(f.data.address)}</p><p>Стоимость: ${f.data.feeKopecks == null ? 'Не согласована' : rub(f.data.feeKopecks / 100)}</p><p>Срок: ${esc(f.data.estimatedDate || 'Не согласован')}</p><form method="post" action="/crm/orders/${o.id}/shipment">${csrf(s)}${hidden('revision', f.revision)}<label>Состояние<select name="state">${Object.entries(shipmentNames).map(([k, v]) => `<option value="${k}"${f.data.state === k ? ' selected' : ''}>${v}</option>`).join('')}</select></label>${input('Перевозчик', 'carrier', f.data.carrier, 'maxlength="100"')}${input('Трек-номер', 'tracking', f.data.tracking, 'maxlength="100"')}<button>Сохранить доставку</button></form></section>
    <details class="box"><summary>Предложить цену и срок покупателю</summary><form method="post" action="/crm/orders/${o.id}/propose">${csrf(s)}${hidden('revision', f.revision)}${d.lines.map(l => input(`${esc(l.title)} — цена за единицу, ₽`, `price_${l.id}`, l.priceRub, 'inputmode="decimal" required')).join('')}${input('Доставка, ₽', 'shippingRub', f.data.feeKopecks == null ? '' : f.data.feeKopecks / 100, 'inputmode="decimal" required')}${input('Срок получения', 'estimatedDate', f.data.estimatedDate, 'maxlength="100" required')}${input('Адрес или пункт выдачи', 'address', f.data.address, 'maxlength="250"')}<button>Сохранить предложение</button></form><p class="muted">Покупатель подтверждает новые условия на странице своего заказа.</p></details>
    ${proposal ? `<div class="box"><p>Предложение ожидает подтверждения: ${rub(proposal.data.totalKopecks / 100)} · ${esc(proposal.data.delivery.estimatedDate)}</p><form method="post" action="/crm/orders/${o.id}/accept">${csrf(s)}${hidden('proposalId', proposal.id)}${input('Основание подтверждения клиента — диалог и время', 'evidence', '', 'maxlength="250" required')}<button>Зафиксировать подтверждение из переписки</button></form></div>` : ''}
    ${s.role === 'owner' ? `<details class="box"><summary>Себестоимость и ожидаемая прибыль</summary><p>${economics.contributionKopecks == null ? 'Прибыль не рассчитана: нет подтверждённой себестоимости.' : `Ожидаемый результат: ${rub(economics.contributionKopecks / 100)} · ${esc(economics.status)}`}</p><p class="muted">${esc(economics.recognitionNote)}</p><form method="post" action="/crm/orders/${o.id}/cost">${csrf(s)}<label>Достоверность<select name="status">${costStatuses.map(k => `<option${k === economics.status ? ' selected' : ''}>${k}</option>`).join('')}</select></label>${input('Закуп товаров заказа, ₽', 'costRub', economics.amount_kopecks == null ? '' : economics.amount_kopecks / 100, 'inputmode="decimal"')}${input('Документ или основание', 'source', economics.source, 'maxlength="250"')}${input('Прямые расходы сверх себестоимости, ₽', 'directRub', (economics.direct_cost_kopecks || 0) / 100, 'inputmode="decimal"')}${area('Что включено в закуп и расходы', 'note', economics.note)}<button>Сохранить расчёт</button></form></details>` : ''}`;
}
