export const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const rub = n => n==null?'Цена по запросу':`${Number(n).toLocaleString('ru-RU')} ₽`;
export const when = n => n?new Date(n).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'}):'—';
export const hidden = (name,value) => `<input type="hidden" name="${esc(name)}" value="${esc(value)}">`;
export const csrf = s => hidden('csrf',s.csrf);
export const channelNames={telegram:'Telegram',avito:'Авито',yandex:'Яндекс Карты',moysklad:'МойСклад'};
export const stateNames={new:'Новый',checking:'Проверяем',confirmed:'Согласован',fulfilling:'Выполняем',completed:'Завершён',cancelled:'Отменён',returned:'Возврат',queued:'В очереди',working:'Отправляем',retry:'Повторим',blocked:'Нужна настройка',unknown:'Нужно проверить результат',published:'Подтверждено',ready:'Выгрузка готова',served:'Файл запрошен',closed:'Закрыто',superseded:'Заменено новой версией'};
const css=`*{box-sizing:border-box}body{max-width:760px;margin:24px auto;padding:0 16px;color:#201821;background:#fff;font:18px/1.5 Georgia,serif}a{color:#0000b8}a:visited{color:#650091}header,footer{text-align:center}h1{font-size:clamp(38px,9vw,64px);line-height:1.15;margin:6px 0 14px;color:#ef350c;text-shadow:2px 2px #ffe100,4px 4px #178b16}h2{font-size:26px}nav{display:flex;gap:16px;justify-content:center;flex-wrap:wrap}hr{border:0;border-top:4px double #111;margin:22px 0}.badge{background:#ffed00;padding:3px 8px}.box,fieldset{border:2px groove #bbb;padding:16px;margin:16px 0;background:#fafafa}.row{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap}.price{color:#650091;font:bold 23px Arial,sans-serif}button,.button{font:16px Arial,sans-serif;min-height:44px;padding:10px 16px;border:3px outset #ddd;background:#eee;color:#201821;cursor:pointer}.primary{background:#7200cb;color:#fff600;border-color:#a420ed;font-weight:bold}input,select,textarea{font:16px Arial,sans-serif;max-width:100%;min-height:44px;padding:8px;border:2px inset #ccc}input:not([type=checkbox]):not([type=hidden]),select,textarea{width:100%}label{display:block;margin:12px 0}input[type=checkbox]{vertical-align:middle;width:20px;min-height:20px}small,.muted{font:14px/1.5 Arial,sans-serif;color:#615862}.notice{border-left:4px solid #7200cb;padding:12px;background:#fffbd6}.error{border-left-color:#a11;color:#811}table{border-collapse:collapse;width:100%;font-size:15px}td,th{text-align:left;padding:8px;border-bottom:1px solid #ddd;vertical-align:top}.scroll{overflow:auto}footer{margin:30px 0;font-size:15px}.trap{position:absolute;left:-10000px}pre{white-space:pre-wrap;overflow-wrap:anywhere}a:focus-visible,button:focus-visible,input:focus-visible{outline:3px solid #0064d2;outline-offset:3px}img{max-width:100%;height:auto}.description{white-space:pre-wrap}.tabs{justify-content:flex-start}summary{cursor:pointer}@media(max-width:480px){body{margin:16px auto}.box{padding:12px}h2{font-size:23px}}`;
export function page(title,body,{admin=false,cart=0,role,notice='',error=false}={}) {
  const nav=admin?`<nav class="tabs"><a href="/crm">Обзор</a><a href="/crm/products">Товары</a><a href="/crm/prices">Цены dev</a><a href="/crm/orders">Заказы</a><a href="/crm/channels">Каналы</a><a href="/">Магазин ↗</a></nav>`:`<nav><a href="/">Каталог</a><a href="/cart">Корзина${cart?` (${cart})`:''}</a><a href="/contacts">Как нас найти</a></nav>`;
  return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Макбучная</title><meta name="description" content="Макбучная — компьютеры в Нижнем Новгороде. Грузинская, 41а. Заказ онлайн."><link rel="icon" href="data:,"><style>${css}</style></head><body><header><small>Добро пожаловать в</small><h1>Макбучную!</h1><p><span class="badge">${admin?'УПРАВЛЕНИЕ МАГАЗИНОМ':'КОМПЬЮТЕРЫ В НИЖНЕМ'}</span></p></header><hr>${nav}<main>${notice?`<p role="status" class="notice${error?' error':''}">${esc(notice)}</p>`:''}${body}</main><footer><hr><p>Нижний Новгород · Грузинская, 41а</p><p><a href="/privacy">Обработка данных</a> · <a href="/terms">Условия заказа</a>${admin?` · ${esc(role==='manager'?'Менеджер':'Владелец')}`:''}</p></footer></body></html>`;
}
export function productCard(p) { return `<article class="box"><h2><a href="/p/${p.id}">${esc(p.title)}</a></h2><p>${esc(p.specification.slice(0,130))}</p><div class="row"><span class="price">${rub(p.priceRub)}</span><a href="/p/${p.id}">Выбрать →</a></div></article>`; }
export function catalogue(products,{q='',category='',p=1,total=0,categories=[]}={}) {
  const params=new URLSearchParams({q,category});
  return `<h2>Выберите свой компьютер</h2><form method="get" action="/"><label>Поиск<input name="q" value="${esc(q)}" maxlength="80" placeholder="Модель, память, цвет"></label><div class="row"><label>Категория<select name="category"><option value="">Все компьютеры</option>${categories.slice(0,6).map(c=>`<option${category===c?' selected':''}>${esc(c)}</option>`).join('')}</select></label><button>Найти</button></div></form>${products.map(productCard).join('')||'<div class="box"><p>Каталог наших компьютеров пополняется.</p><p><a href="https://order.macbookbro.ru/">Подобрать Mac или другой товар на заказ →</a></p><p>Нижний Новгород, Грузинская, 41а.</p></div>'}<nav>${p>1?`<a href="/?${params}&p=${p-1}">← Назад</a>`:''}${p*4<total?`<a href="/?${params}&p=${p+1}">Дальше →</a>`:''}</nav>`;
}
export function productView(p,s) {
  return `<p><a href="/">← Все компьютеры</a></p><h2>${esc(p.title)}</h2><p class="price">${rub(p.priceRub)}</p><p class="description">${esc(p.specification)}</p>${p.photos.length?`<p><a href="/p/${p.id}/photos">Фото компьютера (${p.photos.length}) →</a></p>`:''}<div class="description">${esc(p.description)}</div>${p.warranty?`<p><b>Гарантия:</b> ${esc(p.warranty)}</p>`:''}<form action="/cart/add" method="post">${csrf(s)}${hidden('id',p.id)}<button class="primary">${p.priceRub==null?'Запросить стоимость':'Добавить в корзину'}</button></form><p class="muted">После оформления мы свяжемся с вами и подтвердим заказ и срок получения.</p>`;
}
export function cartView(lines,s) {
  return `<h2>Корзина</h2>${lines.length?`<form action="/cart/update" method="post">${csrf(s)}${lines.map(l=>`<div class="box"><p><b>${esc(l.title)}</b></p><div class="row"><span>${rub(l.priceRub)}</span><label>Количество<input name="qty_${l.id}" type="number" min="0" max="10" value="${l.qty}" aria-label="Количество ${esc(l.title)}"></label></div>${!l.active?'<p>Это предложение закрыто. Уберите его из корзины.</p>':''}</div>`).join('')}<p class="muted">Укажите 0, чтобы убрать товар.</p><button>Обновить корзину</button></form><p class="price">Итого: ${rub(lines.every(l=>l.priceRub!=null)?lines.reduce((v,l)=>v+l.priceRub*l.qty,0):null)}</p><p><a class="button primary" href="/checkout">Оформить заказ →</a></p>`:'<p>Пока здесь пусто. <a href="/">Выберите компьютер</a>.</p>'}`;
}
export function checkoutView(quote,s,values={}) {
  return `<h2>Оформление заказа</h2><div class="box">${quote.lines.map(l=>`<p>${esc(l.title)} × ${l.qty}<br><b>${rub(l.priceRub==null?null:l.priceRub*l.qty)}</b></p>`).join('')}<p class="price">Итого: ${rub(quote.lines.every(l=>l.priceRub!=null)?quote.lines.reduce((v,l)=>v+l.priceRub*l.qty,0):null)}</p></div><form action="/checkout" method="post">${csrf(s)}${hidden('checkoutId',quote.id)}<label>Телефон<input type="tel" name="phone" autocomplete="tel" maxlength="24" value="${esc(values.phone)}" required placeholder="+7 999 123-45-67"></label><label>Имя — необязательно<input name="name" maxlength="100" autocomplete="name" value="${esc(values.name)}"></label><label>Комментарий<textarea name="comment" maxlength="600">${esc(values.comment)}</textarea></label><label>Оплата после подтверждения<select name="payment"><option value="cash"${values.payment!=='invoice'?' selected':''}>Наличные</option><option value="invoice"${values.payment==='invoice'?' selected':''}>Счёт для ИП или организации</option></select></label><label class="trap" aria-hidden="true">Ваш сайт<input name="website" tabindex="-1" autocomplete="off"></label><label><input type="checkbox" name="consent" required> Согласен на <a href="/privacy">обработку данных</a> для выполнения заказа.</label><button class="primary">Отправить заказ</button></form><p class="muted">Оплата на этом шаге не списывается. Мы подтвердим условия и срок получения.</p>`;
}
export function editor(p,recommendations,s) {
  const d=p?.draft || {channels:[],photos:[]};
  const input=(label,name,value='',extra='')=>`<label>${label}<input name="${name}" value="${esc(value)}" ${extra}></label>`;
  const options=recommendations.map(r=>`<option value="${r.key}"${d.recommendationKey===r.key?' selected':''}>${esc(r.label)} — ${rub(r.priceRub)}${r.issues.length?' · нужна проверка':''}</option>`).join('');
  return `<h2>${p?'Карточка компьютера':'Добавить компьютер'}</h2><form method="post" action="/crm/products/save">${csrf(s)}${hidden('id',p?.id||'')}${hidden('revision',p?.revision||0)}${input('Название','title',d.title,'required maxlength="120"')}${input('Категория','category',d.category||'Mac','maxlength="40"')}${input('Бренд','vendor',d.vendor||'Apple','maxlength="50"')}<label>Точная конфигурация dev<select name="recommendationKey"><option value="">Без сопоставления — цена по запросу</option>${options}</select></label><label><input type="checkbox" name="mappingConfirmed"${d.mappingConfirmed?' checked':''}> Проверил модель, память, цвет и остальные характеристики</label><label>Характеристики<textarea name="specification" maxlength="800">${esc(d.specification)}</textarea></label><label>Описание<textarea name="description" rows="6" maxlength="1800">${esc(d.description)}</textarea></label>${input('Условия гарантии','warranty',d.warranty,'maxlength="250"')}<label><input type="checkbox" name="individual"${d.individual?' checked':''}> Отдельный экземпляр компьютера</label><fieldset><legend>После сайта публиковать в</legend>${Object.entries(channelNames).map(([key,label])=>`<label><input type="checkbox" name="channels" value="${key}"${d.channels?.includes(key)?' checked':''}> ${label}</label>`).join('')}</fieldset><details><summary>Сопоставление внешних систем</summary>${input('UUID товара в МойСклад','moyskladId',d.moyskladId)}<label>Тип записи<select name="moyskladType"><option value="product">Товар</option><option value="variant"${d.moyskladType==='variant'?' selected':''}>Модификация</option></select></label>${input('Категория Авито','avitoCategory',d.avitoCategory||'Ноутбуки')}</details><div class="row"><button name="action" value="save">Сохранить черновик</button><button class="primary" name="action" value="publish">Опубликовать на сайте</button></div></form>${p?`<div class="box"><h3>Фотографии</h3>${d.photos.map(f=>`<a href="/media/${f}"><img src="/media/${f}" width="100" alt="Фото компьютера"></a>`).join('')}<form action="/crm/products/${p.id}/photo" method="post" enctype="multipart/form-data">${csrf(s)}${hidden('revision',p.revision)}<label>Добавить фото JPEG, PNG или WebP (до 5 МБ)<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required></label><button>Загрузить фотографию</button></form><p class="muted">После загрузки нажмите «Опубликовать на сайте», чтобы обновить публичные фотографии.</p></div>${p.published?`<p><a href="/p/${p.id}">Посмотреть на сайте ↗</a></p><form action="/crm/products/${p.id}/unpublish" method="post">${csrf(s)}<button>Снять публикацию</button></form>`:''}`:''}`;
}
