export const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const textEsc = v => String(v ?? '').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
export const previewText=(value,bytes)=>{let result='';for(const char of String(value??'')){const next=textEsc(char);if(Buffer.byteLength(result+next)>bytes-3)return result+'…';result+=next;}return result;};
export const rub = n => n==null?'Цена по запросу':`${Number(n).toLocaleString('ru-RU')} ₽`;
export const when = n => n?new Date(n).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'}):'—';
export const hidden = (name,value) => `<input type="hidden" name="${esc(name)}" value="${esc(value)}">`;
export const csrf = s => hidden('csrf',s.csrf);
import { compactShop } from './compact-shop.mjs';
import { macbookFamilies } from './macbook-catalog.mjs';
import { deliveryNames } from './checkout-data.mjs';
export const channelNames={telegram:'Telegram',avito:'Авито',yandex:'Яндекс Карты',moysklad:'МойСклад'};
export const stateNames={new:'Новый',checking:'Проверяем',confirmed:'Согласован',fulfilling:'Выполняем',completed:'Завершён',cancelled:'Отменён',returned:'Возврат',queued:'В очереди',working:'Отправляем',retry:'Повторим',blocked:'Нужна настройка',unknown:'Нужно проверить результат',published:'Подтверждено',ready:'Выгрузка готова',served:'Файл запрошен',closed:'Закрыто',superseded:'Заменено новой версией'};
import { brandCss, layoutCss, shopCss, menuCss, formsCss, productArtCss, catalogCss, storiesCss, accessCss, productCss, responsiveCss, workspaceCss, parserCss, icon, staffNavigation } from './design-system.mjs';
const activeLink=(href,path)=>href==='/crm'?path==='/crm':path===href.replace(/\/$/,'')||path.startsWith(href.replace(/\/$/,'')+'/')||(href==='/crm/contacts'&&path.startsWith('/crm/customers'))||(href==='/crm/desk'&&path.startsWith('/crm/inbox'))||(href==='/crm/integrations'&&path.startsWith('/crm/channels'));
const brand=(href='/')=>`<a class="brand" href="${esc(href)}"><span class="mark">mb</span><span>Макбучная<small>MACBOOKBRO</small></span></a>`;
export const catalogGroups=[['notebooks','Ноутбуки',[['air','Air'],['pro','Pro']]],['desktops','Настольные компьютеры',[['mini','Mac mini'],['studio','Mac Studio']]],['accessories','Аксессуары',[['chargers','Зарядные устройства'],['other','Другие аксессуары']]],['smartphones','Смартфоны',[['iphone','iPhone']]]];
const catalogMenu=()=>`<div id="categories" popover aria-label="Категории каталога">${catalogGroups.map(([id,label,children])=>`<section><a href="${id==='notebooks'?'/#configurations':'/?category='+id}"><b>${label}</b></a>${children.map(([child,name])=>`<a href="/?${['air','pro'].includes(child)?'family':'category'}=${child}">${name}</a>`).join('')}</section>`).join('')}</div>`;
export function page(title,body,{admin=false,auth=false,parser=false,parserSheet='',head='',path='',q='',cart=0,role,username,shopOrigin,session,notice='',error=false}={}) {
  const access=auth||/^\/account\/(login|register|forgot|reset)$/.test(path);
  const product=body.includes('class="product-detail"');
  const catalog=body.includes('class="catalog"');
  const shop=shopOrigin||'';
  const nav=`<form class="site-search" action="${shop}/#configurations" role="search"><input type="search" name="q" value="${esc(q)}" maxlength="80" placeholder="Поиск по каталогу" aria-label="Поиск по каталогу"><button aria-label="Найти">${icon('search')}</button></form><nav class="shop-actions" aria-label="Магазин">${[['/cart',`Корзина${cart?` · ${cart}`:''}`,'cart'],['/account','Войти','user']].map(([href,label,symbol])=>`<a href="${shop+href}" aria-label="${label}"${path===href?' aria-current="page"':''}>${icon(symbol)}<span>${label}</span></a>`).join('')}</nav>`;
  const staffNav=staffNavigation.map(([href,label,symbol],i)=>`${i===7?'<span class="nav-section">Товары и цены</span>':i===9?'<span class="nav-section">Управление</span>':''}<a href="${href}"${activeLink(href,path)?' aria-current="page"':''}>${icon(symbol)}${label}</a>`).join('');
  const staffName=username||(role==='manager'?'Менеджер':'Владелец');
  const sidebar=`<aside class="sidebar">${brand('/crm')}<span class="nav-section">Рабочее место</span><nav aria-label="Разделы CRM">${staffNav}</nav><a class="sidebar-shop" href="${esc(shopOrigin||'/')}">${icon('arrow')}Открыть магазин</a><div class="staff-user"><span class="avatar">${esc(staffName.slice(0,1))}</span><span>${esc(staffName)}<small>${role==='owner'?'Владелец':'Менеджер'}</small></span>${session?`<form method="post" action="/crm/logout">${csrf(session)}<button aria-label="Выйти из CRM" title="Выйти">↪</button></form>`:''}</div></aside>`;
  const header=admin?`<header class="workspace-header"><span class="breadcrumb">Макбучная <span>/ ${esc(title)}</span></span><div class="workspace-account"><span class="workspace-label">${esc(staffName)}</span>${session?`<form class="mobile-logout" method="post" action="/crm/logout">${csrf(session)}<button aria-label="Выйти из CRM">Выйти</button></form>`:''}</div></header>`:`<header class="site-header">${access?brand(shopOrigin||'/'):`<div class="catalog-lockup"><a class="brand" href="${esc(shopOrigin||'/')}">Макбучная</a>${catalog?`<button class="catalog-button" popovertarget="categories">Каталог <span>⌄</span></button>${catalogMenu()}`:`<a class="catalog-button" href="${shop}/#configurations">Каталог</a>`}</div>`}${access?`<a class="muted" href="${esc(shopOrigin||'/')}">← В магазин</a>`:nav}</header>`;
  const footer=admin?'<footer>Макбучная · Рабочее место</footer>':`<footer class="site-footer"><div><strong>Макбучная</strong><a href="${shop}/contacts">Нижний Новгород<br>Грузинская, 41а ↗</a></div><div><h3>Покупателям</h3><a href="${shop}/account">Личный кабинет</a><a href="${shop}/delivery">Доставка и самовывоз</a><a href="${shop}/contacts">О магазине</a></div><div class="footer-bottom"><span>MacBookBro</span><a href="${shop}/privacy">Обработка данных</a><a href="${shop}/terms">Условия заказа</a></div></footer>`;
  const content=`${header}<main id="main-content">${notice?`<p role="${error?'alert':'status'}" class="notice${error?' error':''}">${esc(notice)}</p>`:''}${body}</main>${footer}`;
  const html = `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${previewText(title,100)} · Макбучная</title><meta name="description" content="MacBook. Нижний Новгород."><meta name="theme-color" content="#4438ca"><link rel="icon" href="data:,">${head}<style>${brandCss}${product?'':layoutCss}${admin?'':shopCss}${catalog||product?'':formsCss}${body.includes('class="product-art')||body.includes('class="stories"')?productArtCss:''}${catalog?catalogCss+menuCss:''}${body.includes('class="stories"')?storiesCss:''}${body.includes('class="product-detail"')?productCss:''}${access||body.includes('class="auth"')?accessCss:''}${admin?'':responsiveCss}${admin?workspaceCss:''}${parser?parserCss:''}</style></head><body class="${admin?'crm':'shop'}${access?' access':''}${parser?' parser':''}"${parserSheet?` data-sheet="${esc(parserSheet)}"`:''}><a class="skip-link" href="#main-content">К содержимому</a><div class="shell">${admin?sidebar+`<div class="app-main">${content}</div>`:content}</div></body></html>`;
  return admin ? html : compactShop(html);
}
const laptopArt=(family='air')=>`<div class="product-art" aria-hidden="true"><span class="laptop ${['air','pro','neo'].includes(family)?family:'air'}"></span></div>`;
export function productCard(p) { return `<a class="box product-card" href="${esc(p.href||'/p/'+p.id)}">${laptopArt(p.family)}<h2>${previewText(p.family?p.title.split(' · ')[0]:p.title,96)}</h2><p>${previewText(p.specification,112)}</p><div class="row"><span class="price">${rub(p.priceRub)}</span><span class="button">Выбрать</span></div></a>`; }
export function catalogue(products,{q='',category='',family='',vendor='',p=1,total=0,brands=['Apple']}={}) {
  const params=new URLSearchParams({q,category,family,vendor});
  let brandBytes=0;
  const brandCards=['Apple','Anker','UGREEN','Logitech','Ray-Ban Meta'].map(b=>`<a href="/?vendor=${encodeURIComponent(b)}#configurations"${vendor===b?' aria-current="page"':''}>${previewText(b,28)}</a>`).filter(link=>{const size=Buffer.byteLength(link);if(brandBytes&&brandBytes+size>500)return false;brandBytes+=size;return true;}).join('');
  const selectedGroup=catalogGroups.find(g=>g[0]===category),selectedChild=catalogGroups.flatMap(g=>g[2]).find(c=>c[0]===category);
  const heading=q?'Результаты поиска':selectedGroup?.[1]||selectedChild?.[1]||(['Аксессуары','accessories','chargers','other'].includes(category)?'Аксессуары':family?macbookFamilies.find(f=>f.id===family)?.name||'Каталог':'Каталог MacBook');
  return `<div class="catalog">${!q&&!category&&!family&&!vendor&&p===1?`<section class="stories" aria-label="Разделы магазина"><div class="story account-story"><h2>Личный кабинет</h2><p>Ваши заказы и связь<br>с Макбучной</p><span class="account-art" aria-hidden="true">mb</span><div><a class="button" href="/account/login">Войти</a><a class="button" href="/account">Мои заказы</a></div></div><a class="story desktop-story" href="/order/"><span class="story-label">Предзаказ</span><h2>Новые Mac mini<br>и Mac Studio</h2><span class="desktop-art" aria-hidden="true"></span></a><a class="story air-story" href="/?family=air#configurations"${family==='air'?' aria-current="page"':''}><h2>MacBook Air</h2><span class="laptop air" aria-hidden="true"></span></a><a class="story pro-story" href="/?family=pro#configurations"${family==='pro'?' aria-current="page"':''}><h2>MacBook<br>Pro</h2><span class="laptop pro" aria-hidden="true"></span></a><a class="story accessory-story" href="/?category=accessories#configurations"><h2>Аксессуары</h2><span class="accessory-art" aria-hidden="true"></span></a></section>`:''}<section class="brands" aria-label="Бренды">${brandCards}</section><div class="row catalog-heading" id="configurations"><h1>${textEsc(heading)}</h1><span class="muted">${total} предложений${q||family||category||vendor?' · <a href="/#configurations">Все товары</a>':''}</span></div>${q?`<p>По запросу «${textEsc(q)}»</p>`:''}<div class="grid catalog-grid">${products.map(productCard).join('')}</div>${!products.length?`<div class="box"><h3>${['Аксессуары','accessories','chargers','other'].includes(category)?'Аксессуары под заказ':'Найдём вашу конфигурацию'}</h3><p class="muted">${['Аксессуары','accessories','chargers','other'].includes(category)?'Расскажите, что ищете. Уточним наличие, стоимость и срок доставки.':'Для этого выбора пока нет опубликованных предложений.'}</p><a class="button primary" href="/request${['Аксессуары','accessories','chargers','other'].includes(category)?'?model=Аксессуары':''}">Оставить заявку →</a></div>`:''}<nav class="tabs" aria-label="Страницы каталога">${p>1?`<a href="/?${params}&p=${p-1}#configurations">← Назад</a>`:''}${p*4<total?`<a href="/?${params}&p=${p+1}#configurations">Дальше →</a>`:''}${total?`<span class="muted">${Math.min((p-1)*4+1,total)}–${Math.min(p*4,total)} из ${total}</span>`:''}</nav></div>`;
}
export function productView(p,s) {
  return `<p><a class="muted" href="/">← Все компьютеры</a></p><section class="product-detail">${laptopArt(p.family)}<div><h2>${textEsc(p.title)}</h2><p class="description muted">${textEsc(p.specification)}</p><p class="price">${rub(p.priceRub)}</p>${p.photos.length?`<p><a href="/p/${esc(p.id)}/photos">Фото компьютера (${p.photos.length}) →</a></p>`:''}<div class="description">${textEsc(p.description)}</div>${p.warranty?`<p><b>Гарантия:</b> ${esc(p.warranty)}</p>`:''}<form action="/cart/add" method="post">${csrf(s)}${hidden('id',p.id)}<button class="primary">${p.priceRub==null?'Запросить стоимость':'Добавить в корзину'}</button></form><p class="muted">Заказ и срок получения подтвердит менеджер.</p></div></section>`;
}
export function cartView(lines,s) {
  return `<h2>Корзина</h2>${lines.length?`<form action="/cart/update" method="post">${csrf(s)}${lines.map(l=>`<div class="box"><p><b>${textEsc(l.title)}</b></p><div class="row"><span>${rub(l.priceRub)}</span><label>Количество<input name="qty_${l.id}" type="number" min="0" max="10" value="${l.qty}" aria-label="Количество ${esc(l.title)}"></label></div>${!l.active?'<p>Это предложение закрыто. Уберите его из корзины.</p>':''}</div>`).join('')}<p class="muted">Укажите 0, чтобы убрать товар.</p><button>Обновить корзину</button></form><p class="price">Итого: ${rub(lines.every(l=>l.priceRub!=null)?lines.reduce((v,l)=>v+l.priceRub*l.qty,0):null)}</p><p><a class="button primary" href="/checkout">Оформить заказ →</a></p>`:'<p>Пока здесь пусто. <a href="/">Выберите компьютер</a>.</p>'}`;
}
export function checkoutView(quote,s,values={}) {
  return `<h2>Оформление заказа</h2><div class="box">${quote.lines.map(l=>`<p>${textEsc(l.title.slice(0,90))} × ${l.qty}<br><b>${rub(l.priceRub==null?null:l.priceRub*l.qty)}</b></p>`).join('')}<p class="price">Товары: ${rub(quote.lines.every(l=>l.priceRub!=null)?quote.lines.reduce((v,l)=>v+l.priceRub*l.qty,0):null)}</p></div><form action="/checkout" method="post">${csrf(s)}${hidden('checkoutId',quote.id)}<label>Телефон<input type="tel" name="phone" autocomplete="tel" maxlength="24" value="${esc(values.phone)}" required placeholder="+7 999 123-45-67"></label><label>Имя — необязательно<input name="name" maxlength="100" autocomplete="name" value="${esc(values.name)}"></label><label>Email — необязательно<input type="email" name="email" maxlength="254" autocomplete="email" value="${esc(values.email)}"></label><label>Получение<select name="deliveryMethod">${Object.entries(deliveryNames).map(([k,v])=>`<option value="${k}"${(values.deliveryMethod||'pickup')===k?' selected':''}>${v}</option>`).join('')}</select></label><label>Город — для отправки по России<input name="deliveryCity" maxlength="100" autocomplete="address-level2" value="${esc(values.deliveryCity)}"></label><label>Адрес или пункт выдачи — можно уточнить позже<input name="deliveryAddress" maxlength="250" autocomplete="street-address" value="${esc(values.deliveryAddress)}"></label><p class="muted">Самовывоз: Грузинская, 41а. Стоимость и срок доставки согласуем с вами; они пока не включены в сумму товаров.</p><label>Комментарий<textarea name="comment" maxlength="600">${textEsc(values.comment)}</textarea></label><label>Оплата после подтверждения<select name="payment"><option value="cash"${values.payment!=='invoice'?' selected':''}>Наличные</option><option value="invoice"${values.payment==='invoice'?' selected':''}>Счёт для ИП или организации</option></select></label><label class="trap" aria-hidden="true">Ваш сайт<input name="website" tabindex="-1" autocomplete="off"></label><label><input type="checkbox" name="consent" required> Согласен на <a href="/privacy">обработку данных</a> для выполнения заказа.</label><button class="primary">Отправить заказ</button></form><p class="muted">Регистрация не нужна. Оплата на этом шаге не списывается.</p>`;
}
export function editor(p,recommendations,s) {
  const d=p?.draft || {channels:[],photos:[]};
  const input=(label,name,value='',extra='')=>`<label>${label}<input name="${name}" value="${esc(value)}" ${extra}></label>`;
  const options=recommendations.map(r=>`<option value="${r.key}"${d.recommendationKey===r.key?' selected':''}>${esc(r.label)} — ${rub(r.priceRub)}${r.issues.length?' · нужна проверка':''}</option>`).join('');
  return `<h2>${p?'Карточка компьютера':'Добавить компьютер'}</h2><form method="post" action="/crm/products/save">${csrf(s)}${hidden('id',p?.id||'')}${hidden('revision',p?.revision||0)}${input('Название','title',d.title,'required maxlength="120"')}${input('Категория','category',d.category||'Mac','maxlength="40"')}${input('Бренд','vendor',d.vendor||'Apple','maxlength="50"')}<label>Точная конфигурация dev<select name="recommendationKey"><option value="">Без сопоставления — цена по запросу</option>${options}</select></label><label><input type="checkbox" name="mappingConfirmed"${d.mappingConfirmed?' checked':''}> Проверил модель, память, цвет и остальные характеристики</label><label>Характеристики<textarea name="specification" maxlength="800">${esc(d.specification)}</textarea></label><label>Описание<textarea name="description" rows="6" maxlength="1800">${esc(d.description)}</textarea></label>${input('Условия гарантии','warranty',d.warranty,'maxlength="250"')}<label><input type="checkbox" name="individual"${d.individual?' checked':''}> Отдельный экземпляр компьютера</label><fieldset><legend>После сайта публиковать в</legend>${Object.entries(channelNames).map(([key,label])=>`<label><input type="checkbox" name="channels" value="${key}"${d.channels?.includes(key)?' checked':''}> ${label}</label>`).join('')}</fieldset><details><summary>Сопоставление внешних систем</summary>${input('UUID товара в МойСклад','moyskladId',d.moyskladId)}<label>Тип записи<select name="moyskladType"><option value="product">Товар</option><option value="variant"${d.moyskladType==='variant'?' selected':''}>Модификация</option></select></label>${input('Категория Авито','avitoCategory',d.avitoCategory||'Ноутбуки')}</details><div class="row"><button name="action" value="save">Сохранить черновик</button><button class="primary" name="action" value="publish">Опубликовать на сайте</button></div></form>${p?`<div class="box"><h3>Фотографии</h3>${d.photos.map(f=>`<a href="/media/${f}"><img src="/media/${f}" width="100" alt="Фото компьютера"></a>`).join('')}<form action="/crm/products/${p.id}/photo" method="post" enctype="multipart/form-data">${csrf(s)}${hidden('revision',p.revision)}<label>Добавить фото JPEG, PNG или WebP (до 5 МБ)<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required></label><button>Загрузить фотографию</button></form><p class="muted">После загрузки нажмите «Опубликовать на сайте», чтобы обновить публичные фотографии.</p></div>${p.published?`<p><a href="/p/${p.id}">Посмотреть на сайте ↗</a></p><form action="/crm/products/${p.id}/unpublish" method="post">${csrf(s)}<button>Снять публикацию</button></form>`:''}`:''}`;
}
