import { writeFile, readFile, mkdir } from 'node:fs/promises';
import { cheapest, type Offer } from './model.js';
import { technichno, rifastore } from './adapters.js';
const demo: Offer[] = JSON.parse(await readFile('data/offers.json','utf8'));
const live = process.env.LIVE === '1' ? (await Promise.all([technichno.fetchOffers(), rifastore.fetchOffers()])).flat() : [];
const offers = [...demo, ...live];
await mkdir('data/private', { recursive: true, mode: 0o700 });
await writeFile('data/private/legacy-cli-offers.json', JSON.stringify(offers, null, 2), { mode: 0o600 });
await writeFile('data/private/legacy-cli-cheapest.json', JSON.stringify(cheapest(offers), null, 2), { mode: 0o600 });
console.log(`Wrote ${offers.length} legacy offers and ${cheapest(offers).length} product groups outside the master snapshot`);
